export const products = {
	page: 1,
	totalPages: 3,
	itemsPerPage: 5,
	totalItems: 15,
	cartItems: [
		{
			id: "1",
			name: "Blue Partyhat",
			price: 450.0,
			originalPrice: 622.5,
			imageUrl: "https://example.com/blue-partyhat.jpg",
			inStock: true,
			onSale: true,
			quantity: 1,
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: "2",
			name: "Red Partyhat",
			price: 400.0,
			originalPrice: 550.0,
			imageUrl: "https://example.com/red-partyhat.jpg",
			inStock: true,
			onSale: true,
			quantity: 2,
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: "3",
			name: "Green Partyhat",
			price: 425.0,
			originalPrice: 600.0,
			imageUrl: "https://example.com/green-partyhat.jpg",
			inStock: false,
			onSale: false,
			quantity: 0,
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: "4",
			name: "Yellow Partyhat",
			price: 380.0,
			originalPrice: 525.0,
			imageUrl: "https://example.com/yellow-partyhat.jpg",
			inStock: true,
			onSale: true,
			quantity: 3,
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: "5",
			name: "Purple Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://example.com/purple-partyhat.jpg",
			inStock: true,
			onSale: false,
			quantity: 1,
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
	],
};

export const HeaderItems = [
	{
		label: "Currency",
		url: "#",
	},
	{
		label: "Items",
		url: "#",
	},
	{
		label: "Accounts",
		url: "#",
	},
	{
		label: "Services",
		url: "#",
	},
	{
		label: "Swap",
		url: "#",
	},
	{
		label: "Sell",
		url: "#",
	},
]