import { DollarSign, Euro, IndianRupee, JapaneseYen, PoundSterling } from "lucide-react";
import { HeaderItem, MenuItem, Option, Products } from "./types";
import { getRandomNumber } from "./utils";
import { v4 as uuidv4 } from "uuid";

export enum PlatformBadge {
	RS3 = "RS3",
	OSRS = "OSRS",
	COD = "COD",
	CODBO6 = "CODBO6",
	DeadBDL = "DeadBDL",
	Fortnite = "Fortnite",
	DiabloIV = "DiabloIV",
}

const products: Products = {
	page: 1,
	totalPages: 3,
	itemsPerPage: 10,
	totalItems: 15,
	cartItems: [
		{
			id: uuidv4(),
			name: "Vessek if Hatred - DLC",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-vessel_wrx54t.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Verdant Pool Teleport",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-verdant-pool-teleport_akbwb3.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 Platinum",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-1000-platinum_qmh1ll.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Vessek if Hatred - DLC",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-vessel_wrx54t.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Verdant Pool Teleport",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-verdant-pool-teleport_akbwb3.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 Platinum",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-1000-platinum_qmh1ll.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Vessek if Hatred - DLC",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-vessel_wrx54t.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Verdant Pool Teleport",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-verdant-pool-teleport_akbwb3.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 Platinum",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-1000-platinum_qmh1ll.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Vessek if Hatred - DLC",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-vessel_wrx54t.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Verdant Pool Teleport",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-verdant-pool-teleport_akbwb3.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 Platinum",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-1000-platinum_qmh1ll.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Vessek if Hatred - DLC",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-vessel_wrx54t.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Verdant Pool Teleport",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-verdant-pool-teleport_akbwb3.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 Platinum",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-1000-platinum_qmh1ll.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Vessek if Hatred - DLC",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-vessel_wrx54t.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Verdant Pool Teleport",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-verdant-pool-teleport_akbwb3.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 Platinum",
			price: getRandomNumber(150.0, 780.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738264045/div-1000-platinum_qmh1ll.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DiabloIV,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "HELLRAISER - DLC",
			price: getRandomNumber(1050.0, 1320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256134/dbdly-hellraiser_iijo0a.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "HELLRAISER - DLC",
			price: getRandomNumber(1050.0, 1320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256134/dbdly-hellraiser_iijo0a.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "HELLRAISER - DLC",
			price: getRandomNumber(1050.0, 1320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256134/dbdly-hellraiser_iijo0a.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "HELLRAISER - DLC",
			price: getRandomNumber(1050.0, 1320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256134/dbdly-hellraiser_iijo0a.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: 425.0,
			originalPrice: 600.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: false,
			onSale: false,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Yellow Partyhat",
			price: getRandomNumber(300.0, 520.0),
			originalPrice: 525.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738259706/OSRS-Yellow_partyhat_p1bh6z.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Yellow Partyhat",
			price: getRandomNumber(300.0, 520.0),
			originalPrice: 525.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738259706/OSRS-Yellow_partyhat_p1bh6z.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Yellow Partyhat",
			price: getRandomNumber(300.0, 520.0),
			originalPrice: 525.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738259706/OSRS-Yellow_partyhat_p1bh6z.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Yellow Partyhat",
			price: getRandomNumber(300.0, 520.0),
			originalPrice: 525.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738259706/OSRS-Yellow_partyhat_p1bh6z.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: false,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: false,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: false,
			onSale: false,
			quantity: 0,
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: false,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 v-bucks",
			price: getRandomNumber(450.0, 640.0),
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/Fortnite-1000_v-bucks_mw4bbt.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.Fortnite,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 v-bucks",
			price: getRandomNumber(450.0, 640.0),
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/Fortnite-1000_v-bucks_mw4bbt.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.Fortnite,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 v-bucks",
			price: getRandomNumber(450.0, 640.0),
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/Fortnite-1000_v-bucks_mw4bbt.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.Fortnite,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 v-bucks",
			price: getRandomNumber(450.0, 640.0),
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/Fortnite-1000_v-bucks_mw4bbt.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.Fortnite,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "HELLRAISER - DLC",
			price: getRandomNumber(1050.0, 1320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256134/dbdly-hellraiser_iijo0a.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "HELLRAISER - DLC",
			price: getRandomNumber(1050.0, 1320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256134/dbdly-hellraiser_iijo0a.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "HELLRAISER - DLC",
			price: getRandomNumber(1050.0, 1320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256134/dbdly-hellraiser_iijo0a.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "HELLRAISER - DLC",
			price: getRandomNumber(1050.0, 1320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256134/dbdly-hellraiser_iijo0a.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: 425.0,
			originalPrice: 600.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: false,
			onSale: false,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Yellow Partyhat",
			price: getRandomNumber(300.0, 520.0),
			originalPrice: 525.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738259706/OSRS-Yellow_partyhat_p1bh6z.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Yellow Partyhat",
			price: getRandomNumber(300.0, 520.0),
			originalPrice: 525.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738259706/OSRS-Yellow_partyhat_p1bh6z.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Yellow Partyhat",
			price: getRandomNumber(300.0, 520.0),
			originalPrice: 525.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738259706/OSRS-Yellow_partyhat_p1bh6z.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Yellow Partyhat",
			price: getRandomNumber(300.0, 520.0),
			originalPrice: 525.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738259706/OSRS-Yellow_partyhat_p1bh6z.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: false,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: false,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: false,
			onSale: false,
			quantity: 0,
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: false,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 v-bucks",
			price: getRandomNumber(450.0, 640.0),
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/Fortnite-1000_v-bucks_mw4bbt.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.Fortnite,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 v-bucks",
			price: getRandomNumber(450.0, 640.0),
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/Fortnite-1000_v-bucks_mw4bbt.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.Fortnite,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 v-bucks",
			price: getRandomNumber(450.0, 640.0),
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/Fortnite-1000_v-bucks_mw4bbt.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.Fortnite,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 v-bucks",
			price: getRandomNumber(450.0, 640.0),
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/Fortnite-1000_v-bucks_mw4bbt.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.Fortnite,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "HELLRAISER - DLC",
			price: getRandomNumber(1050.0, 1320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256134/dbdly-hellraiser_iijo0a.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "HELLRAISER - DLC",
			price: getRandomNumber(1050.0, 1320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256134/dbdly-hellraiser_iijo0a.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "HELLRAISER - DLC",
			price: getRandomNumber(1050.0, 1320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256134/dbdly-hellraiser_iijo0a.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "HELLRAISER - DLC",
			price: getRandomNumber(1050.0, 1320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256134/dbdly-hellraiser_iijo0a.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: 425.0,
			originalPrice: 600.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: false,
			onSale: false,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Yellow Partyhat",
			price: getRandomNumber(300.0, 520.0),
			originalPrice: 525.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738259706/OSRS-Yellow_partyhat_p1bh6z.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Yellow Partyhat",
			price: getRandomNumber(300.0, 520.0),
			originalPrice: 525.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738259706/OSRS-Yellow_partyhat_p1bh6z.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Yellow Partyhat",
			price: getRandomNumber(300.0, 520.0),
			originalPrice: 525.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738259706/OSRS-Yellow_partyhat_p1bh6z.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Yellow Partyhat",
			price: getRandomNumber(300.0, 520.0),
			originalPrice: 525.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738259706/OSRS-Yellow_partyhat_p1bh6z.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: false,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: false,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: false,
			onSale: false,
			quantity: 0,
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: false,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 v-bucks",
			price: getRandomNumber(450.0, 640.0),
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/Fortnite-1000_v-bucks_mw4bbt.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.Fortnite,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 v-bucks",
			price: getRandomNumber(450.0, 640.0),
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/Fortnite-1000_v-bucks_mw4bbt.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.Fortnite,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 v-bucks",
			price: getRandomNumber(450.0, 640.0),
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/Fortnite-1000_v-bucks_mw4bbt.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.Fortnite,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 v-bucks",
			price: getRandomNumber(450.0, 640.0),
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/Fortnite-1000_v-bucks_mw4bbt.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.Fortnite,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "HELLRAISER - DLC",
			price: getRandomNumber(1050.0, 1320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256134/dbdly-hellraiser_iijo0a.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "HELLRAISER - DLC",
			price: getRandomNumber(1050.0, 1320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256134/dbdly-hellraiser_iijo0a.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "HELLRAISER - DLC",
			price: getRandomNumber(1050.0, 1320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256134/dbdly-hellraiser_iijo0a.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "HELLRAISER - DLC",
			price: getRandomNumber(1050.0, 1320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256134/dbdly-hellraiser_iijo0a.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "GHOSTFACE - DLC",
			price: getRandomNumber(700.0, 1520.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/dbdly-ghostface_ho4wrp.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.DeadBDL,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Fury Weapon",
			price: getRandomNumber(150.0, 320.0),
			originalPrice: 322.5,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/cod-green-fury_aissuh.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.CODBO6,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Red Partyhat",
			price: getRandomNumber(400, 500),
			originalPrice: 550.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256599/OSRS-Red_partyhat_bqyanu.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: 425.0,
			originalPrice: 600.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: false,
			onSale: false,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Green Partyhat",
			price: getRandomNumber(425.0, 1000.0),
			originalPrice: 1100.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Green_partyhat_hizvxf.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Yellow Partyhat",
			price: getRandomNumber(300.0, 520.0),
			originalPrice: 525.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738259706/OSRS-Yellow_partyhat_p1bh6z.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Yellow Partyhat",
			price: getRandomNumber(300.0, 520.0),
			originalPrice: 525.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738259706/OSRS-Yellow_partyhat_p1bh6z.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Yellow Partyhat",
			price: getRandomNumber(300.0, 520.0),
			originalPrice: 525.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738259706/OSRS-Yellow_partyhat_p1bh6z.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Yellow Partyhat",
			price: getRandomNumber(300.0, 520.0),
			originalPrice: 525.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738259706/OSRS-Yellow_partyhat_p1bh6z.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: "RS3",
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: false,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: false,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: false,
			onSale: false,
			quantity: 0,
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: false,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "Blue Partyhat",
			price: 500.0,
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/OSRS-Blue_partyhat_aqvyjd.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.OSRS,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 v-bucks",
			price: getRandomNumber(450.0, 640.0),
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/Fortnite-1000_v-bucks_mw4bbt.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.Fortnite,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 v-bucks",
			price: getRandomNumber(450.0, 640.0),
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/Fortnite-1000_v-bucks_mw4bbt.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.Fortnite,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 v-bucks",
			price: getRandomNumber(450.0, 640.0),
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/Fortnite-1000_v-bucks_mw4bbt.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.Fortnite,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
		{
			id: uuidv4(),
			name: "1000 v-bucks",
			price: getRandomNumber(450.0, 640.0),
			originalPrice: 650.0,
			imageUrl: "https://res.cloudinary.com/dw4ecbwo9/image/upload/v1738256133/Fortnite-1000_v-bucks_mw4bbt.webp",
			inStock: true,
			onSale: true,
			quantity: getRandomNumber(1, 25),
			platformBadge: PlatformBadge.Fortnite,
			description: "Lorem ipsum dolor sit amet consectetur sadipscing elitr.",
		},
	],
};

export const fetchProducts = async (): Promise<Products> => {
	return new Promise(resolve => {
		setTimeout(() => {
			resolve(products);
		}, 200);
	});
};

export const headerItems: HeaderItem[] = [
	{
		label: "Currency",
		url: "#",
	},
	{
		label: "Items",
		url: "#",
	},
	{
		label: "Accounts",
		url: "#",
	},
	{
		label: "Services",
		url: "#",
	},
	{
		label: "Swap",
		url: "#",
	},
	{
		label: "Sell",
		url: "#",
	},
];

export const menuItems: MenuItem[] = [
	{ id: "usd", label: "USD", icon: <DollarSign className="h-4 w-4" /> },
	{ id: "eur", label: "EUR", icon: <Euro className="h-4 w-4" /> },
	{ id: "gbp", label: "GBP", icon: <PoundSterling className="h-4 w-4" /> },
	{ id: "yen", label: "YEN", icon: <JapaneseYen className="h-4 w-4" /> },
	{ id: "rup", label: "Ruppe", icon: <IndianRupee className="h-4 w-4" /> },
];

export const menuItemsMobile: Option[] = [
	{ value: "usd", label: "USD" },
	{ value: "eur", label: "EUR" },
	{ value: "gbp", label: "GBP" },
	{ value: "yen", label: "YEN" },
	{ value: "rup", label: "Ruppe" },
];

export const priceOptions: Option[] = [
	{ label: "All", value: "" },
	{ label: "$0 - $50", value: "0-50" },
	{ label: "$50 - $100", value: "50-100" },
	{ label: "$100 - $200", value: "100-200" },
	{ label: "$200 - $300", value: "200-300" },
	{ label: "$300 - $500", value: "300-500" },
	{ label: "$500 - $1000", value: "500-1000" },
	{ label: "$1000+", value: "1000+" },
];

export const sortByOptions: Option[] = [
	{ label: "Name (A-Z)", value: "name-asc" },
	{ label: "Name (Z-A)", value: "name-desc" },
	{ label: "Price (Low to Hight)", value: "price-asc" },
	{ label: "Price (High a Low)", value: "price-desc" },
	{ label: "Availability (In Stock First)", value: "inStock" },
];
